### PR TITLE
Automatic chrome version matching

### PR DESCRIPTION
**Pull request by xylix**
Builds on https://github.com/rasjani/webdrivermanager/pull/22, adding linux and macos support for chrome installed version detection. 

- [x] default to detected version if available instead of latest webdriver

## Questions before merging
- Is it okay for just chromedriver to default to 'compatible'  instead of latest if no version is specified? Should the API document that different drivers may default to different versions if no version is specified?

### CODE REVIEW

**Comment by osrjv** [comment]
I cleaned up the PR a bit and added "compatible" option for chrome version in addition to "latest". Kept the latest as default so the change should be backwards compatible.

**Comment by rasjani** [comment]
Ill check this over the weekend and merge .. will probably make some refactoring afterwards..

**Comment by osrjv** [comment]
Cool, thanks. We can also use this directly from the fork if you have some reservations about merging as-is

**Comment by rasjani** [comment]
> if you have some reservations about merging as-is

Point for refactoring is to make the "compatible" mode a generic feature of all browsers but only for now to implement it for chrome so it shouldn't block or break things for you.. Otherwise patch looks good for now.

**Comment by rasjani** [comment]
>     * Is it okay for just chromedriver to default to 'compatible'  instead of latest if no version is specified? 

Since wdm isnt "1.0" yet, i dont see a huge problem. I would assume that usecase of most people is "get the working one" and `compatible` is probably even better than the `latest`. I'll look around a bit on this matter. I would think that graceful fallback from `compatible` to `latest`, for example if the browser specific implementation does not know how to query the compatibility *or* all implemented cases do not find the browser or required information for them, using latest then shouldn't be a problem . 

> Would the API document that different drivers may default to different versions if no version is specified?

Lets see, I'll write something ...

**Pull request merged**
