### PR TITLE
Fallback download methods

### PR DESCRIPTION
**Pull request by quarckster**
Gecko driver and Opera Chromium driver are hosted on github. Sometimes downloading fails due to api rate limit exceeding. This PR adds a new fallback download method via parsing the github release pages.

### CODE REVIEW

**Comment by rasjani** [comment]
merged and released in 0.4.0

**Comment by rasjani** [comment]
Btw, i noticed few bug in the pr.

* when trying to download geckodriver in macos, downloading fails because bitness is not in the release file where as operachromium does have it .. 
* get_download_path in opera side did not include similar rate limit action as gecko side ..

**Comment by quarckster** [comment]
@rasjani I don't have macos, therefore I couldn't test it there. I'll fix `get_download_path` in opera.

**Comment by rasjani** [comment]
fixed both already, no need to dedicate time for it ..

**Pull request merged**
